### PR TITLE
feat: prevent infinite refreshes and exiting race condition

### PR DESCRIPTION
**Pull request by angeloashmore**
This PR addresses two related issues:

1. Previews can sometimes get into a state where the page refreshes endlessly. See #66 for details and how to reproduce the issue.
2. When two preview windows for the same session are open, and one is exited, the other window will re-enable previews. This happens because the non-exited window is checking for preview updates on an interval and upserts (i.e. re-enables) the preview cookie that was deleted by the exiting window.

These issues are resolved by treating the preview state from the prismic.io iframe as the source of truth.

- Before starting a preview session, check if a ref is present in the latest preview state. If not, there is no active preview session. The toolbar does not need to refresh the page.
- On each interval where the toolbar checks for preview updates, first check if the preview cookie exists. If it does not, exit the preview.

This has the nice side-effect of exiting previews across all windows at once from a single toolbar "X" click.

## Reproduction to test PR

This repo can be used as a test: https://github.com/angeloashmore/prismic-toolbar-issue-66-repro

### CODE REVIEW

**Review by lihbr — APPROVED** [review]
Look good to me, will test!

Can you review too @arnaudlewis?

**Comment by angeloashmore** [comment]
Awesome! Here's a repo to test the issue: https://github.com/angeloashmore/prismic-toolbar-issue-66-repro

**Review by arnaudlewis — APPROVED** [review]

**Review by matheusrufinos — APPROVED** [review]

**Review by Klynger — APPROVED** [review]

**Review by GustavoSchuler — APPROVED** [review]

**Review by Leoffta — APPROVED** [review]

**Review by matheusportoo — APPROVED** [review]

**Comment by matheusrufinos** [comment]
Hello, do you have a date for merge/release this pull request? 🙏

**Comment by lihbr** [comment]
Hey there, it should be released this week 👌

**Comment by scottgulliver** [comment]
Hi, just wondering if this is still planned for this/next week? We're currently blocked by this, and it comes at a crucial time where our client is evaluating CMS platforms 😅

**Comment by lihbr** [comment]
Hey there,

First of all, I'm sorry for the extra delay, back and forth, and lack of visibility that has been going on with this pull request.

I synced with our DevOps team this morning about it, they scheduled it for Monday morning, if it doesn't happen then I'll make sure to sync with them again to have it shipped.

Thank you for your understanding 🙏

**Comment by lihbr** [comment]
This PR has been deployed 🎉

**Comment by lihbr** [comment]
Yes, the toolbar is automatically updated for everyone. If you check the network tab you should see `iframe.html` being served from a 4.0.8 folder.

**Pull request merged**
